### ISSUE TITLE
i cant use of for 1.19.3 its not 

### ISSUE THREAD

**Issue by PixelAxolotl** [aridevelopment-de/fabric-packet-logger#14]
A potential solution has been determined:
	 - Replace mod 'Packet Logger' (packetlogger) 1.1.2 with any version that is compatible with:
		 - minecraft 1.19.3
I have tried every version but it still didn't load for 1.19.3

**Comment by Ari24-cb24** [comment]
I think I have some versions wrong in the fabric properties, will check in a bit. Also, make sure you're using the latest version 1.4.0

**Comment by PixelAxolotl** [comment]
ya i used 1.4.0 it didnt work too

**Comment by Ari24-cb24** [comment]
Have created a seperate branch for 1.19.3, it's now supported but my main focus is still on 1.19.4 atm. Should work fine tho. The version is also already available at modrinth
