### ISSUE TITLE
Using a chunked-based approach when sending data via websocket

### ISSUE THREAD

**Issue by Ari24-cb24** [aridevelopment-de/fabric-packet-logger#17]
To improve ws performance, the following approach should be considered:
- A chunk of Packets should be collected, compressed and then send via websocket
- Packet data should be reduced by a lot (e.g.)
    - Do not include packet metadata (such as packet name), only the packet id
    - Field names should be reduced to a single character
    - When connecting, a mapping is being send via websocket which includes the actual names of the variables
    - Maybe considering a shorter format than json

**Comment by BasiqueEvangelist** [comment]
Couldn't you use a port of DataInputStream to JS for metadata?

**Comment by lbirkert** [comment]
> To improve ws performance, the following approach should be considered:
> 
>     * A chunk of Packets should be collected, compressed and then send via websocket
> 
>     * Packet data should be reduced by a lot (e.g.)
>       
>       * Do not include packet metadata (such as packet name), only the packet id
>       * Field names should be reduced to a single character
>       * When connecting, a mapping is being send via websocket which includes the actual names of the variables
>       * Maybe considering a shorter format than json

Packets could be sent to the frontend using the original protocol form prepended with the packet state (s>c/c>s) and some other metadata (received at, ...) encoded into a header.

**Comment by lbirkert** [comment]
Websockets should be able to handle this stream of binary data

**Comment by Ari24-cb24** [comment]
Implemented at #19   
I still use json data but in a more convenient way and with much less data at all. Might switch over to a stream of binary data but this should be sufficient for now as I need to develop some other things in the meantime.
